trigger:
- master

pr:
- master
jobs: 
- job: build
  pool:
    name: Azure Pipelines
    vmImage: ubuntu-latest
    demands:
    - npm
    - java

  steps:
  - task: Npm@1
    displayName: 'npm install'
    inputs:
      workingDir: ./fur2feathers
      verbose: false

  - task: Npm@1
    displayName: build
    inputs:
      command: custom
      workingDir: ./fur2feathers
      verbose: false
      customCommand: 'run build-prod'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: ./fur2feathers/dist/fur2feathers/
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'

- job: test

  pool:
    vmImage: ubuntu-latest

  steps:
  
  - task: Npm@1
    displayName: 'npm install'
    inputs:
      workingDir: ./fur2feathers
      verbose: false
  
  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'f2f-ng'
      organization: '2002-feb24-net'
      scannerMode: 'MSBuild'
      projectKey: '2002-feb24-net_Fur2FeathersNg-project3'
      projectName: 'f2f-ng'

  - script: npx ng test --browsers ChromeHeadless --no-watch --code-coverage
    workingDirectory: ./fur2feathers
    continueOnError: true
    displayName: ng test
  - task: SonarCloudAnalyze@1
    displayName: sonarcloud analysis run

  - task: SonarCloudPublish@1
    displayName: sonarcloud results build publish