
# ui accessible at localhost:4200 / 192.168.99.100:4200

version: '3.7'

services:

  web:
    build: fur2feathers
    image: f2f-ng:1.0
    ports:
      - 4200:80
    networks:
      - default

networks:
  default: